get 'knowledge_hub', to: 'wiki_hub#index', as: 'knowledge_hub'
get 'knowledge_hub/search', to: 'wiki_hub#search'
get 'knowledge_hub/search/suggestions', to: 'wiki_hub#search_suggestions', as: 'search_suggestions_knowledge_hub'
get 'knowledge_hub/related_pages', to: 'wiki_hub#related_pages', as: 'related_pages_knowledge_hub'
get 'knowledge_hub/create', to: 'wiki_hub#quick_create', as: 'quick_create_knowledge_hub'
post 'knowledge_hub/create', to: 'wiki_hub#quick_create'
post 'knowledge_hub/bulk_action', to: 'wiki_hub#bulk_action', as: 'bulk_action_knowledge_hub'
get 'knowledge_hub/templates', to: 'wiki_hub_templates#index', as: 'knowledge_hub_templates'
get 'knowledge_hub/templates/create', to: 'wiki_hub_templates#create_from_hub', as: 'create_from_hub_knowledge_hub_templates'
post 'knowledge_hub/templates/create', to: 'wiki_hub_templates#create_from_hub'
get 'knowledge_hub/templates/:id/analytics', to: 'wiki_hub_templates#analytics', as: 'analytics_knowledge_hub_template'
get 'knowledge_hub/templates/:id/use', to: 'wiki_hub_templates#use', as: 'use_knowledge_hub_template'
post 'knowledge_hub/templates/:id/use', to: 'wiki_hub_templates#use'
post 'knowledge_hub/templates/:id/preview', to: 'wiki_hub_templates#preview', as: 'preview_knowledge_hub_template'
get 'knowledge_hub/templates/:id', to: 'wiki_hub_templates#show', as: 'knowledge_hub_template'
post 'knowledge_hub/templates/:id/copy', to: 'wiki_hub_templates#copy', as: 'knowledge_hub_copy_template'
get 'knowledge_hub/lessons', to: 'wiki_hub_lessons#index', as: 'knowledge_hub_lessons'
get 'knowledge_hub/graph', to: 'wiki_hub_graph#index', as: 'knowledge_hub_graph'
get 'knowledge_hub/backlinks', to: 'wiki_hub_backlinks#index', as: 'knowledge_hub_backlinks'

get 'projects/:project_id/wiki_hub', to: 'wiki_hub#project_index', as: 'project_wiki_hub'
get 'projects/:project_id/wiki_hub/search', to: 'wiki_hub#project_search', as: 'project_wiki_hub_search'
get 'projects/:project_id/wiki_hub/metadata', to: 'wiki_hub#metadata'
get 'projects/:project_id/wiki/:id/metadata', to: 'wiki_hub_metadata#show'
patch 'projects/:project_id/wiki/:id/metadata', to: 'wiki_hub_metadata#update'

get 'admin/wiki_hub', to: 'wiki_hub_admin#index'
post 'admin/wiki_hub/rebuild', to: 'wiki_hub_admin#rebuild'
get 'admin/wiki_hub/health', to: 'wiki_hub_admin#health'

get 'my/wiki_hub_homepage', to: 'wiki_hub_homepage#show'
patch 'my/wiki_hub_homepage', to: 'wiki_hub_homepage#update'
