production:
  adapter: postgresql
  database: <%= ENV.fetch('DB_NAME', 'redmica') %>
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  username: <%= ENV.fetch('DB_USER', 'redmica') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'redmica') %>
  encoding: unicode

test:
  adapter: postgresql
  database: <%= ENV.fetch('DB_TEST_NAME', 'redmica_test') %>
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  username: <%= ENV.fetch('DB_USER', 'redmica') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'redmica') %>
  encoding: unicode
